### ISSUE TITLE
Pulls only Massachusetts

### ISSUE THREAD

**Issue by demarcomf** [LeOndaz/zillow-scraper#1]
I noticed that the map bounds have all directional coordinates. how could this be changed to check several regions of the country?

**Comment by LeOndaz** [comment]
Yes map is bounded by a specific region got by searching for "Cap Code, MA" in zillow, the script was created for the sake of the job (Getting data of Barnstable County Cape Cod from Zillow), so it makes sense that it does what was only needed, I didn't generalize the idea to work on whole zillow.com
